sudo: required
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install: 

  - echo "$AZURE_PASSWORD" | az login -u "$AZURE_USERNAME" --password-stdin
  - az aks get-credentials --resource-group $RESOURCE_GROUP --name $CLUSTER_NAME
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t t4christ/react-kubernetes -f ./docker-react/Dockerfile.dev ./docker-react


script: 
  - docker run t4christ/react-kubernetes npm test -- --coverage

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
